name: 'oortclouds-docs'

on:
  push:
    branches:
      - master

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@master
      - name: 'install depc'
        run: yarn install
      - name: 'Start Work'
        run: yarn docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.OORT_DOCS_TOKEN }}
          publish_dir: public
